### ISSUE TITLE
Thank you for your contribution

### ISSUE THREAD

**Issue by 2821840032** [bartofzo/NativeTrees#3] opened 2023-07-13 08:01 UTC
It's perfect.
The performance is also outstanding and perfectly matches DOTS.
NativeOctree Constructor bounds argument It doesn't seem to work.
It also has no ability to delete or update points or AABB locations
Otherwise I have to keep clearing it
Thank you

**Comment by bartofzo** [comment] 2023-07-17 08:19
Can you clarify about the bounds not working?

And yes, there is no update by design. You have to clear and rebuild the tree. But it can be done quite fast in most cases.

**Comment by bartofzo** [comment] 2023-09-11 08:57
Closing this issue for now

**Closed as completed by bartofzo** 2023-09-11 08:57 UTC
